name: "Check README Links"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "README.md"
      - ".github/workflows/links_checker.yml"

jobs:
  linkChecker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Read broken links
        id: read_links
        run: |
          if grep -q "Errors" ./lychee/out.md && grep -q "[0-9]*" ./lychee/out.md; then
            broken_links=$(cat ./lychee/out.md)
            echo "broken_links<<EOF" >> $GITHUB_ENV
            echo "$broken_links" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "broken_links=All links in the README.md are working fine! 🎉" >> $GITHUB_ENV
          fi

      - name: Create Comment for Broken Links
        if: env.broken_links != 'All links in the README.md are working fine! 🎉' # Only run if there are broken links
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Link Checker Report:**  
            The following links are broken in the README.md:  
            ```markdown
            ${{ env.broken_links }}
            ```

      - name: Create Comment for No Broken Links
        if: env.broken_links == 'All links in the README.md are working fine! 🎉' # Only run if all links are fine
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Link Checker Report:**  
            All links in the README.md are working fine! 🎉
