name: "Check docs links"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - ".github/workflows/links_checker.yml"
  pull_request:
    paths:
      - "README.md"
      - ".github/workflows/links_checker.yml"

jobs:
  linkChecker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Read broken links
        id: read_links
        run: |
          if [ -s ./lychee/out.md ]; then
            echo "broken_links<<EOF" >> $GITHUB_ENV
            cat ./lychee/out.md >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "broken_links=All links are working fine!" >> $GITHUB_ENV
          fi

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Link Checker Report:**  
            ${{ env.broken_links }}
